name: Test, build, and deploy

on:
  push:
    branches:
      - 'main'
    tags: []  # Explicit: do not run workflow on pushing tags


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}  # e.g. Test, Build, Deploy-refs/heads/main
  cancel-in-progress: false


jobs:
  test_build_deploy:
    if: github.repository == 'wikisim/wikisim-frontend'
    runs-on: ubuntu-latest

    steps:
      - name: ___________________________ SETUP ___________________________
        run: echo Setup

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: ___________________________ TEST ___________________________
        run: echo Test

      - name: Run Jest
        run: npx jest --ci

      - name: ___________________________ BUILD ___________________________
        run: echo Build

      - name: Build website
        run: pnpm run build

      - name: ___________________________ DEPLOY ___________________________
        run: echo Deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload to s3
        run: |
          aws s3 cp ./dist s3://wikisim.org/ --recursive

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1X2Y3Z4ABCDEFG --paths "/*"
